<a href="https://colab.research.google.com/github/institutohumai/cursos-python/blob/master/AnalisisDeDatos/1_Indexing/Indexing.ipynb"> <img src='https://colab.research.google.com/assets/colab-badge.svg' /> </a>
<div align="center"> Recordá abrir en una nueva pestaña </div>

In [2]:
# Siempre al principio, importamos las librerías.
import pandas as pd
import numpy as np

# Indexación y Agregación

Tabla de Contenidos

    I. Análisis de datos con Pandas
    II. Los objetos fundamentales de Pandas
        I. Series
        II. DataFrames
        III. Índices
    III. Exploración
        I. Filtrando un DataFrame (Indexing)
            I. Boolean Indexing
                I. Máscara booleana
                II. Máscara booleana con muchas condiciones
            II. Boolean indexing con query()
            III. Fancy Indexing
        II. Funciones de Agregación
    IV. Otros análisis descriptivos
        I. Para las variables numéricas
        II. Para las variables categóricas
        III. Ordenar por columnas y limitar la cantidad de resultados
    V. Anexo: volviendo al tema de la vectorización

## Exploración

Vamos a analizar datos de una fuente real. Los ingresos de los funcionarios son información pública que se libera anualmente en el <a href='https://data.buenosaires.gob.ar/dataset/sueldo-funcionarios'>portal de datos abiertos</a> de GCBA.  

En general los 4 primeros pasos para analizar un data set son:
1. Leerlo
2. Consultar cuáles son las columnas
3. Extraer una muestra
4. Verificar cuántos registros tiene

## 1- Para leer el data set usamos la función de pandas read_csv

Con esta función podemos leer archivos que estén en una url pública o en una ubicación del disco accesible desde la Jupyter Notebook.

In [ ]:
df_sueldo_funcionarios = pd.read_csv('http://cdn.buenosaires.gob.ar/datosabiertos/datasets/sueldo-funcionarios/sueldo_funcionarios_2019.csv')

## 2- Consultamos las columnas

In [ ]:
df_sueldo_funcionarios.columns

Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')

## 3- Extraemos una muestra

In [ ]:
df_sueldo_funcionarios.sample(5)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
104,20-14699669-9,2019,4,MOCCIA,FRANCO,Ministerio de Desarrollo Urbano y Transporte,249661.60,0.0,249661.60,NaN
324,27-24030362-6,2019,11,TAGLIAFERRI,GUADALUPE,Ministerio de Hábitat y Desarrollo Humano,275089.75,0.0,275089.75,NaN
23,20-26781618-3,2019,1,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,0.0,204017.27,NaN
295,27-17593512-1,2019,10,MONTIEL,MARIA LETICIA,SECR Legal y Técnica,267913.50,0.0,267913.50,NaN
291,20-24941711-5,2019,10,MURA,MARTIN,Ministerio de Economía y Finanzas,275089.75,0.0,275089.75,NaN

## 4- Consultamos la cantidad de filas y de columnas

In [ ]:
# La propiedad shape nos devuelve una tupla (filas,columnas)
df_sueldo_funcionarios.shape

(385, 10)

## Vectorización con Pandas

Pandas es una de las librerías de Python más usadas para análisis de datos. El nombre pandas viene de "Panel Data Analysis" y su funcionalidad permite hacer operaciones sobre datos que se encuentran en memoria de manera eficiente.

Pandas es útil para trabajar sobre datos tabulares, con dos condiciones importantes:

I. Los datos se encuentran enteramente en la memoria RAM. Con lo cual, el tamaño de los datos que podemos manipular está limitado por el hardware. Como regla de pulgar, es una buena práctica no ocupar más de 1/3 de la memoria RAM de nuestro dispositivo con el dataset. Así, si estamos trabajando localmente en una notebook con 8GB de memoria RAM no es recomendable procesar datasets de más de 2.33GB.

II. En pandas, las operaciones sobre filas y columnas son, en general, eficientes porque se hacen de forma "vectorizada". En realidad esta optimización, se hace desde numpy, una librería para realizar operaciones matemáticas que se utilizó a su vez para escribir pandas.

Las operaciones vectorizadas son las que se realizan en bloque en vez de caso por caso. Las computadoras de hoy tienen la capacidad de recibir muchas instrucciones juntas y procesar varias de ellas a la vez. Por ejemplo, si nuestro hardware tiene la capacidad de procesar 4 operaciones juntas, el resultado de vectorizar una operación matemática es el siguiente:

<img src = 'https://storage.googleapis.com/humai-datasets/aws_s3/analisis_de_datos/1_Indexing/vectorizacion.png' />


En el primer caso hay que hacer 5 operaciones y en el segundo caso sólo dos.

Es importante entender, entonces, que Pandas trabaja de esta manera y que por eso es una de las herramientas más elegidas para manipular datos en memoria.

In [ ]:
df_sueldo_funcionarios["aguinaldo_porcentaje"] = (df_sueldo_funcionarios["aguinaldo_ii"] * 100) / df_sueldo_funcionarios["asignacion_por_cargo_i"]
df_sueldo_funcionarios[df_sueldo_funcionarios["observaciones"].notnull()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones,aguinaldo_porcentaje
29,20-25567686-6,2019,1,BENEGAS,FERNANDO,SECR Coordinación General,204017.27,0.00,204017.27,alta 01/01/2019,0.000000
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019,16.666667
343,27-13221055-7,2019,12,BOU PEREZ,ANA MARIA,Ministerio de Salud,82526.92,121497.97,204024.89,baja al 9/12,147.222228
344,27-30744939-6,2019,12,FERRERO,GENOVEVA,SECR Administración de Seguridad y Emergencias,74991.86,110404.68,185396.54,baja al 9/12,147.222219
345,20-14699669-9,2019,12,MOCCIA,FRANCO,Ministerio de Desarrollo Urbano y Transporte,82526.92,121497.97,204024.89,baja al 9/12,147.222228
346,20-16891528-5,2019,12,NACHON,MARCELO JORGE,SECR de Medios,80374.05,118328.46,198702.51,baja al 9/12,147.222219
347,27-24030362-6,2019,12,TAGLIAFERRI,GUADALUPE,Ministerio de Desarrollo Humano y Hábitat,82526.92,121497.97,204024.89,baja al 9/12,147.222228
348,20-22709722-2,2019,12,LOPEZ,MATIAS,SECR Desarrollo Ciudadano,74991.86,110404.68,185396.54,baja al 9/12,147.222219
349,20-16461252-0,2019,12,GONZALEZ BERNALDO DE QUIROS,FERNAN,Ministerio de Salud,192562.83,16046.90,208609.73,alta desde el 10/12,8.333332
350,27-31925246-6,2019,12,MIGLIORE,MARIA,Ministerio de Desarrollo Humano y Hábitat,192562.83,16046.90,208609.73,alta desde el 10/12,8.333332
351,20-24563562-2,2019,12,GESUALDO,GUSTAVO ALFREDO,SECR Desarrollo Ciudadano,174981.00,14581.75,189562.75,alta desde el 10/12,8.333333
352,20-26932366-4,2019,12,GARCIA RESTA,ALVARO,SECR Desarrollo Urbano,174981.00,14581.75,189562.75,alta desde el 10/12,8.333333
353,27-28755948-3,2019,12,MUZZIO,MARIA CLARA,Ministerio de Espacio Público e Higiene Urbana,192562.83,16046.90,208609.73,alta desde el 10/12,8.333332
354,20-20008464-1,2019,12,GIUSTI,JOSE LUIS,UPE Transferencia de Funciones y Facultades en...,74991.86,110404.68,185396.54,baja al 9/12,147.222219
355,20-20008464-1,2019,12,GIUSTI,JOSE LUIS,Ministerio de Desarrollo Económico y Producción,192562.83,16046.90,208609.73,alta desde el 10/12,8.333332
356,20-17110752-1,2019,12,MACCHIAVELLI,EDUARDO ALBERTO,Ministerio de Espacio Público e Higiene Urbana,82526.92,107743.49,190270.41,baja al 9/12,130.555569
357,20-17110752-1,2019,12,MACCHIAVELLI,EDUARDO ALBERTO,SECR Ambiente,192562.83,16046.90,208609.73,alta desde el 10/12,8.333332
358,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,SS Comunicacion,74991.86,110404.68,185396.54,baja al 9/12,147.222219
359,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,"SECR Comunicación, Contenidos y Participación ...",187539.45,15628.29,203167.74,alta desde el 10/12,8.333335
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12,147.222219
361,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SECR de Medios,187539.45,15628.29,203167.74,alta desde el 10/12,8.333335
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12,147.222219
363,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,187539.45,15628.29,203167.74,alta desde el 10/12,8.333335
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12,8.333335

In [ ]:
df_sueldo_funcionarios["aguinaldo_porcentaje"].mean()

np.float64(11.141268657896722)

## Los objetos fundamentales de Pandas

### Series

Las series son "columnas" que de una tabla que están asociadas a un índice y a un nombre. Igual que una lista común de Python es una secuencia de elementos ordenados, pero a diferencia de la lista está asociada a más información.

In [ ]:
# Las series se pueden crear a partir de una lista
serie = pd.Series(['a','b','c'])

In [ ]:
# Propiedades importantes de las series
print('Tipo de objetos que tiene ', serie.dtype)
print('Nombre ', serie.name)
print('Index ',serie.index)
print('Valores ',serie.values)

Tipo de objetos que tiene  object
Nombre  None
Index  RangeIndex(start=0, stop=3, step=1)
Valores  ['a' 'b' 'c']

## DataFrames

Los DataFrames son "tablas", compuestas por varias "columnas" o series que comparten todas un mismo índice. En general los DataFrames se crean a partir de leer tablas de archivos (pueden ser en formato json o csv) pero a veces también se crean a partir de listas de diccionarios o de otras maneras.

Los DataFrames tienen un objeto Index que describe los nombres de columnas y otro objeto Index que describen los nombres de las filas.

In [3]:
# Leemos un dataset público
df = pd.read_csv('http://cdn.buenosaires.gob.ar/datosabiertos/datasets/sueldo-funcionarios/sueldo_funcionarios_2019.csv')

In [ ]:
# Propiedades importantes de los dataframes
print('Columnas ', df.columns)
print('Index ', df.index)
print('Dimensiones ',df.shape)

Columnas  Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')
Index  RangeIndex(start=0, stop=385, step=1)
Dimensiones  (385, 10)

In [ ]:
# Consultar las primeras filas
df.head()

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.0,197745.80,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.0,197745.80,NaN
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.0,224516.62,NaN
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN

Si queremos extraer una serie del DataFrame, podemos hacerlo de la misma forma en que extraemos un valor de un diccionario.

In [ ]:
serie_mes = df['mes']

In [ ]:
type(serie_mes)

pandas.core.series.Series

In [ ]:
print(serie_mes)

0       1
1       1
2       1
3       1
4       1
       ..
380    12
381    12
382    12
383    12
384    12
Name: mes, Length: 385, dtype: int64

## Índices

Los índices acompañan a las series y a los Data Frames. Son conjuntos ordenados e inmutables de elementos

In [ ]:
df.index

RangeIndex(start=0, stop=385, step=1)

In [ ]:
df.columns

Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')

In [ ]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [ ]:
ind[1] = 0

TypeError: Index does not support mutable operations

### Ejercicio
Exploren el dataset público que se encuentra en la siguiente url: https://storage.googleapis.com/humai-datasets/aws_s3/analisis_de_datos/1_Indexing/titanic.csv ¿De qué se trata? ¿Cuántas filas tiene? ¿Cuántas columnas? Al leerlo, pueden almacenarlo en la variable df_titanic.

In [4]:
df_titanic = pd.read_csv(" https://storage.googleapis.com/humai-datasets/aws_s3/analisis_de_datos/1_Indexing/titanic.csv", header=0, sep="|", encoding="utf-8", skipinitialspace=True)

In [ ]:
print(df_titanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [ ]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## Filtrando un DataFrame (Indexing)

Hay muchas técnicas para filtrar un DataFrame. Podemos querer filtrar por columnas o por filas, por posición o por nombre. También podemos querer filtrar por condiciones que se cumplen o no. Cuando no queremos filtrar sobre una dimensión (filas o columnas) usamos ":" para seleccionar todo.


<img src='https://github.com/institutohumai/cursos-python/blob/master/AnalisisDeDatos/1_Indexing/img/indexing.png?raw=1' style='height:350px' />

### Boolean Indexing

Supongamos que queremos tomar el dataset de funcionarios y quedarnos únicamente con los que pertenecen al Ministerio de Cultura.
Para eso lo que hacemos es indexar al DataFrame por una condición booleana. Eso implica que debemos crear una serie compuesta por valores True y False para aplicarla como índice a las filas.

Los operadores que sirven para evaluar condiciones sobre las series son:


| S  | Descripción   | S  | Descripción   |   |
|----|---------------|----|---------------|---|
| >= | Mayor o Igual | <= | Menor o Igual |   |
| == | Igual         | != | Distinto      |   |
| >  | Mayor         | <  | Menor         |   |

#### Máscara booleana

Veamos lo que pasa cuando le aplicamos a una serie una condición que devuelve un booleano

In [14]:
df['anio'] != 2019

0      False
1      False
2      False
3      False
4      False
       ...
380    False
381    False
382    False
383    False
384    False
Name: anio, Length: 385, dtype: bool

In [16]:
mascara_booleana = df['anio'] != 2019

Nos devuelve una serie de la misma longitud que la original y que contiene sólo valores True o False.

In [17]:
type(mascara_booleana)

pandas.core.series.Series

In [19]:
mascara_booleana.shape

(385,)

In [18]:
mascara_booleana.dtype

dtype('bool')

Ahora seleccionemos entonces, los registros que corresponden al Ministerio de Cultura.

In [ ]:
df_min_cul = df.loc[df['reparticion'] == 'Ministerio de Cultura',:]

In [ ]:
# Veamos la cantidad de casos
df_min_cul.shape

Algo que puede llegar a confundir sobre el Indexing en Pandas es que en algunos casos se puede ser menos explícito a la hora de filtrar. Por ejemplo si ponemos una condición Booleana, pandas asume que el tipo de indexing es loc y que el filtro es sobre las filas y no sobre las columnas:

In [ ]:
df_min_cul = df[df['reparticion'] == 'Ministerio de Cultura']

In [ ]:
df_min_cul.shape

Probemos con otra condición.

### Ejercicio

Traer todos los sueldos de la segunda mitad del año...

In [ ]:
df_sal_2da_mitad_anio = df_sueldo_funcionarios.loc[df_sueldo_funcionarios["mes"] > 6]
print(df_sal_2da_mitad_anio.shape)
df_sal_2da_mitad_anio.sample(4)

(197, 11)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones,aguinaldo_porcentaje
318,27-13092400-5,2019,11,FREDA,MONICA BEATRIZ,Sindicatura General de la Ciudad de Buenos Aires,275089.75,0.0,275089.75,NaN,0.0
290,20-14699669-9,2019,10,MOCCIA,FRANCO,Ministerio de Desarrollo Urbano y Transporte,275089.75,0.0,275089.75,NaN,0.0
299,20-22366623-0,2019,10,COSTANTINO,SERGIO GABRIEL,SECR Integración Social Para Personas Mayores,249972.87,0.0,249972.87,NaN,0.0
234,20-16891528-5,2019,8,NACHON,MARCELO JORGE,SECR de Medios,256657.23,0.0,256657.23,NaN,0.0

### Ejercicio
Volviendo al DataFrame del Titanic ¿Cuántos pasajeros sobrevivieron y cuántos no? ¿Cuántos pagaron una tarifa menor a 25?

In [ ]:
df_titanic.sample(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
407,408,1,2,"Richards, Master. William Rowe",male,3.0,1,1,29106,18.7500,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,NaN,S

In [ ]:
print(f"Survived: {len(df_titanic.loc[df_titanic["Survived"] == 1])}")

print(f"Not survived: {len(df_titanic.loc[df_titanic["Survived"] == 0])}")

print(f"less than 25 : {len(df_titanic.loc[df_titanic["Fare"] < 25])}")

Survived: 342
Not survived: 549
less than 25 : 557

In [ ]:
df_titanic_survived = df_titanic[df_titanic["Survived"] == 1]
print(f"survived: {df_titanic_survived.shape[0]}")

df_titanic_not_survived = df_titanic[df_titanic["Survived"] == 0]
print(f"not survived {df_titanic_not_survived.shape[0]}")

df_titanic_fare_less_than_25 = df_titanic[df_titanic["Fare"] < 25]
print(f"less than 25: {df_titanic_fare_less_than_25.shape[0]}")

survived: 342
not survived 549
less than 25: 557

In [ ]:
print(f"survived: {(df_titanic["Survived"] == 1).sum()}")

print(f"not survived {(df_titanic["Survived"] == 1).sum()}")

print(f"less than 25: {(df_titanic["Fare"] < 25).sum()}")

survived: 342
not survived 342
less than 25: 557

#### Máscara booleana con muchas condiciones

Ahora tratemos de filtrar el dataset por dos condiciones: por ejemplo tomar los sueldos de abril de la secretaria de innovación.
Para eso tenemos que combinar dos máscaras booleanas con una condición.

| S | Descripcion        | S  | Descripcion |   |
|---|--------------------|----|-------------|---|
| & | AND (y)            | \| | OR (o)      |   |
| ^ | XOR (o exclusivo)  | ~  | NOT (no)    |   |



Por ejemplo: seleccionemos los casos donde o bien se haya cobrado aguinaldo o bien el salario total haya sido mayor que 240.000, pero no las dos cosas.

In [5]:
df[(df['total_salario_bruto_i_+_ii'] > 240000) ^ (df['aguinaldo_ii'] > 0)]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019
97,27-24483014-0,2019,4,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,249661.60,0.00,249661.60,NaN
98,20-13872301-2,2019,4,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.00,249661.60,NaN
100,27-13221055-7,2019,4,BOU PEREZ,ANA MARIA,Ministerio de Salud,249661.60,0.00,249661.60,NaN
...,...,...,...,...,...,...,...,...,...,...
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
361,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SECR de Medios,187539.45,15628.29,203167.74,alta desde el 10/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12
363,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,187539.45,15628.29,203167.74,alta desde el 10/12
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

Ahora veamos los sueldos de febrero de la SECR Ciencia, Tecnologia e Innovacion.

In [6]:
df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019

### Boolean indexing con query()

La sintaxis que se utiliza para hacer Boolean indexing es un poco repetitiva. Noten que filtrar (aún en su expresión más corta sin loc ni especificar filas o columnas) implica ESCRIBIR DOS VECES el nombre del dataset. Para crear un shortcut, Pandas ofrece la función .query()

In [7]:
df_cult = df.query('reparticion == "Ministerio de Cultura"')
df_cult.head(5)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN
36,20-25641207-2,2019,2,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN
68,20-25641207-2,2019,3,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,231167.76,0.0,231167.76,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.0,249661.60,NaN
130,20-25641207-2,2019,5,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.0,249661.60,NaN

También se puede hacer query sobre múltiples condiciones.

In [8]:
df2 = df.query('asignacion_por_cargo_i > 240000 & aguinaldo_ii > 0')

In [9]:
df2.shape

(34, 10)

### Ejercicio: Piensen cómo traducir a la sintaxis de query, estas consultas que ya hicimos:

In [11]:
# df_sem2 = df[df['mes'] > 6]
df_sem2 = df.query('mes > 6')
df_sem2.shape
df_sem2.head(5)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
188,20-17692128-6,2019,7,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,228396.40,0.0,228396.40,NaN
189,20-17735449-0,2019,7,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,228396.40,0.0,228396.40,NaN
190,27-24483014-0,2019,7,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,263531.98,0.0,263531.98,NaN
191,20-13872301-2,2019,7,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.0,263531.98,NaN
192,20-25641207-2,2019,7,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,263531.98,0.0,263531.98,NaN

In [13]:
# df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]
df2 = df.query(" mes == 2 & reparticion == 'SECR Ciencia, Tecnologia e Innovacion' ")
df2.shape
df2

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019

### Fancy Indexing

Ahora vamos a quedarnos con un subconjunto de columnas del DataFrame.

In [20]:
df_view = df.loc[:,['anio','mes']]

In [21]:
df_view.shape

(385, 2)

Existe una forma menos explícita de hacer esta misma operación. Si pasamos una lista al indexing, pandas asume que el tipo de indexing es loc y que el filtro es sobre las columnas y no las filas:

In [22]:
df_view = df[['anio','mes']]

In [23]:
df_view.shape

(385, 2)

Fíjense lo que pasa si tratamos de acceder a filas utilizando una lista de nombres, en este caso [0,1].

In [24]:
# Incorrecto
df_view = df[[3,8]]

KeyError: "None of [Index([3, 8], dtype='int64')] are in the [columns]"

Nos da un error porque cuando pasamos únicamente una lista al indexing, pandas asume que queremos un set de columnas y si los nombres no existen, da error. La forma correcta de hacerlo es pasar una lista de índices y explicitar que vamos a indizar con loc y que seleccionamos todas las columnas.

In [25]:
# Correcto
df_view = df.loc[[3,8],:]

In [26]:
df_view

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN
8,20-22293873-3,2019,1,MIGUEL,FELIPE OSCAR,Jefatura de Gabinete de Ministros,224516.62,0.0,224516.62,NaN

### Ejercicio. Volviendo al ejemplo del titanic...

1) ¿Cuántos hombres y mujeres sobrevivieron?

2) ¿Cuántos menores de 18 años había? ¿Cuántos sobrevivieron?

3) Seleccionen únicamente las columnas Sex y Survived y almacenenlas en un nuevo DataFrame que se llame df_titanic_subset.

In [27]:
df_titanic = pd.read_csv(" https://storage.googleapis.com/humai-datasets/aws_s3/analisis_de_datos/1_Indexing/titanic.csv", header=0, sep="|", encoding="utf-8", skipinitialspace=True)
df_titanic.sample(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
372,373,0,3,"Beavan, Mr. William Thomas",male,19.0,0,0,323951,8.0500,NaN,S
362,363,0,3,"Barbara, Mrs. (Catherine David)",female,45.0,0,1,2691,14.4542,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C

In [48]:
df_titanic_survivors = df_titanic[df_titanic["Survived"] == 1]
df_titanic_survivors_by_sex = df_titanic_survivors["Sex"].value_counts()
df_titanic_survivors_by_sex

Sex
female    233
male      109
Name: count, dtype: int64

In [58]:

df_titanic_under_18 = (df_titanic['Age'] < 18).sum()
print(df_titanic_under_18)
print(len(df_titanic_survivors.query("Survived == 1 & Age < 18")))

113
61

In [65]:
df_titanic_subset = df_titanic[["Survived","Sex"]]
df_titanic_subset.shape

(891, 2)

In [66]:
df_titanic_subset.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

## Funciones de Agregación

Utilizando Pandas podemos aplicar funciones a nivel de columna. Algunas funciones predefinidas son la media, el desvío estándar y la sumatoria, el valor máximo y el mínimo.

Algunas de las funciones de agregación más comunes son:

<ul>
    <li>min</li>
    <li>max</li>
    <li>count</li>
    <li>sum</li>
    <li>prod</li>
    <li>mean</li>
    <li>median</li>
    <li>mode</li>
    <li>std</li>
    <li>var</li>
</ul>

In [67]:
df['mes'].max()

12

In [68]:
df['asignacion_por_cargo_i'].mean()

np.float64(234234.36800000002)

In [69]:
df['asignacion_por_cargo_i'].std()

35043.16008466176

In [70]:
df['total_salario_bruto_i_+_ii'].sum()

np.float64(97988834.36000001)

Podemos combinar los filtros que vimos antes con las funciones de agregación para responder preguntas cómo ¿Cuál fue en gasto en asignaciones de funcionarios para la Secretaría de Medios 2019? ¿Y para la de Justicia y Seguridad?

In [71]:
df[df['reparticion'] == 'SECR de Medios']['total_salario_bruto_i_+_ii'].sum()

np.float64(3232402.25)

In [72]:
df[df['reparticion'] == 'SECR Justicia y Seguridad']['total_salario_bruto_i_+_ii'].sum()

np.float64(3029551.7300000004)

In [74]:
df_titanic[df_titanic["Survived"] == 1]["Sex"].value_counts()

Sex
female    233
male      109
Name: count, dtype: int64

Ahora respondamos algunas preguntas: ¿Quién o quiénes del dataset cobran el salario más alto? ¿Y el más bajo?

In [75]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].max()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [76]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].min()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
344,27-30744939-6,2019,12,FERRERO,GENOVEVA,SECR Administración de Seguridad y Emergencias,74991.86,110404.68,185396.54,baja al 9/12
348,20-22709722-2,2019,12,LOPEZ,MATIAS,SECR Desarrollo Ciudadano,74991.86,110404.68,185396.54,baja al 9/12
354,20-20008464-1,2019,12,GIUSTI,JOSE LUIS,UPE Transferencia de Funciones y Facultades en...,74991.86,110404.68,185396.54,baja al 9/12
358,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,SS Comunicacion,74991.86,110404.68,185396.54,baja al 9/12
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12

## Otros análisis descriptivos

Pandas viene con algunas funciones built-in para ayudar al análisis descriptivo.

## Para las variables numéricas

In [77]:
df.describe()

,anio,mes,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii
count,385.0,385.000000,385.000000,385.000000,385.000000
mean,2019.0,6.631169,234234.368000,20282.084883,254516.452883
std,0.0,3.539077,35043.160085,45248.840725,51434.987870
min,2019.0,1.000000,74991.860000,0.000000,185396.540000
25%,2019.0,4.000000,224516.620000,0.000000,224516.620000
50%,2019.0,7.000000,239470.360000,0.000000,245811.620000
75%,2019.0,10.000000,249972.870000,0.000000,263531.980000
max,2019.0,12.000000,275089.750000,170855.560000,445945.310000

## Para las variables categóricas

In [78]:
df['reparticion'].value_counts()

reparticion
Ministerio de Salud                                               13
SECR de Medios                                                    13
SECR Justicia y Seguridad                                         13
SECR Desarrollo Ciudadano                                         13
Vicejefatura de Gobierno                                          12
Jefe de Gobierno                                                  12
Ministerio de Desarrollo Urbano y Transporte                      12
Jefatura de Gabinete de Ministros                                 12
Ministerio de Gobierno                                            12
SECR Integración Social y Urbana                                  12
SECR Planificación, Evaluación y Coordinación de Gestión          12
Procuración General de la Ciudad de Buenos Aires                  12
Ministerio de Cultura                                             12
Sindicatura General de la Ciudad de Buenos Aires                  12
Consejo de los Derechos de Niñas, Niños y Adoles - Presidencia    12
UPE Transferencia de Funciones y Facultades en Materia de Seg.    12
Ente de Turismo Ley Nº 2627                                       12
SS Contenidos                                                     12
SS Comunicacion                                                   12
SECR Integración Social Para Personas Mayores                     12
SECR Administración de Seguridad y Emergencias                    12
SECR Legal y Técnica                                              12
SECR General y de Relaciones Internacionales                      11
Ministerio de Hábitat y Desarrollo Humano                         11
Ministerio de Economía y Finanzas                                 11
Ministerio de Ambiente y Espacio Público                          11
Ministerio de Educación e Innovación                              11
SECR Transporte                                                   11
SECR Cultura Ciudadana y Función Pública                          11
SECR Atención y Gestión Ciudadana                                 11
SECR Coordinación General                                         11
SECR Ciencia, Tecnologia e Innovacion                              2
Ministerio de Desarrollo Humano y Hábitat                          2
Ministerio de Espacio Público e Higiene Urbana                     2
SECR Desarrollo Urbano                                             1
Ministerio de Desarrollo Económico y Producción                    1
SECR Ambiente                                                      1
SECR Comunicación, Contenidos y Participación Ciudadana            1
SECR Atención Ciudadana y Gestión Comunal                          1
Ministerio de Educación                                            1
Ministerio de Hacienda y Finanzas                                  1
SECR Innovación y Transformación Digital                           1
SECR Transformación Cultural                                       1
SECR Transporte y Obras Públicas                                   1
SECR General y Relaciones Internacionales                          1
SECR Asuntos Estratégicos                                          1
Name: count, dtype: int64

### Ejercicio: Volviendo al ejemplo del Titanic.

1) ¿Cuál era la edad promedio de los pasajeros de cada clase (Pclass)?

2) ¿Cuál fue la tarifa que pagaron en promedio los hombres? ¿Y las mujeres?

3) ¿Cuánto pagaron en total los pasajeros de primera clase para subir al Titanic? ¿Y los de tercera?

4) ¿Cuántos pasajeros había en cada tipo de clase?

In [79]:
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [95]:
# Cuál era la edad promedio de los pasajeros de cada clase (Pclass)
p_class1 = df_titanic[df_titanic["Pclass"] == 1]['Age'].mean().round(2)
p_class2 = df_titanic[df_titanic["Pclass"] == 2]['Age'].mean().round(2)
p_class3 = df_titanic[df_titanic["Pclass"] == 3]['Age'].mean().round(2)
print(f"Clase 1: {p_class1}\nClase 2: {p_class2}\nClase 3: {p_class3}")

promedio_edad_por_clase = df_titanic.groupby("Pclass")["Age"].mean().round(2)
promedio_edad_por_clase

Clase 1: 38.23
Clase 2: 29.88
Clase 3: 25.14

Pclass
1    38.23
2    29.88
3    25.14
Name: Age, dtype: float64

In [96]:
# ¿Cuál fue la tarifa que pagaron en promedio los hombres? ¿Y las mujeres?
df_titanic.groupby("Sex")["Fare"].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [97]:
# ¿Cuánto pagaron en total los pasajeros de primera clase para subir al Titanic? ¿Y los de tercera?

df_titanic.query("Pclass != 2").groupby("Pclass")["Fare"].sum()

Pclass
1    18177.4125
3     6714.6951
Name: Fare, dtype: float64

In [100]:
# ¿Cuántos pasajeros había en cada tipo de clase?
df_titanic.groupby("Pclass")["PassengerId"].count().sort_values(ascending=False)

Pclass
3    491
1    216
2    184
Name: PassengerId, dtype: int64

## Ordenar por columnas y limitar la cantidad de resultados

Otra forma de resolver el problema de encontrar el mayor y el menos es con el método sort_values. Este método puede recibir un valor único (nombre de columna) o una lista (con varias columnas) y un orden asc o desc. Por default el orden es asc.

Si combinamos el ordenamiento con el método head() para limitar la cantidad de resultados, podemos encontrar los N primeros.

In [101]:
# Recordemos cómo abrir la documentación de un método
df.sort_values?

In [102]:
# Calculamos el máximo
df.sort_values('total_salario_bruto_i_+_ii',ascending=False).head(1)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [103]:
# Calculamos el mínimo
df.sort_values('total_salario_bruto_i_+_ii').head(1)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
358,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,SS Comunicacion,74991.86,110404.68,185396.54,baja al 9/12

## Anexo: volviendo al tema de la vectorización

¿Por qué es tan importante trabajar con Pandas y no con funciones escritas por nosotros en Python nativo y que procesen los datos dentro de un for loop?

Por un lado está la comodidad. Hay mucha funcionalidad que ya está desarrollada en Pandas. Existen funciones que resuelven muchos de los problemas clásicos de manipular datos: agrupar, sumarizar, sacar estadísticas, filtrar, etc. Pero además hay una razón de performance.

Veamos una demostración de que vectorizar es más eficiente. Vamos a crear dos listas de 1.000.000 de números aleatorios cada una y vamos a tratar de multiplicar elemento por elemento con pandas y sin pandas:

In [104]:
lista1 = list(np.random.randint(1, 100, 1000000))
lista2 = list(np.random.randint(1, 100, 1000000))

In [105]:
%%timeit
for x,y in zip(lista1,lista2):
    x * y

69.7 ms ± 826 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Ahora probemos hacer lo mismo con dos series de Pandas

In [106]:
serie1 = pd.Series(lista1)
serie2 = pd.Series(lista2)

In [107]:
%%timeit
resultado = serie1 * serie2

2.45 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Conclusión: la operación vectorizada es <strong> más de 70 veces más rápida.</strong>